set encoding=UTF-8

set number

set nocompatible

set mouse=a

set background=dark

syntax enable

syntax on

set hlsearch

set expandtab

set tabstop=4

set shiftwidth=4

set softtabstop=4

set showmatch

set incsearch

set autoindent
set smartindent

set rnu

set hidden

filetype on
filetype plugin on
filetype indent on

" When vim is opened, open NERDTree
" autocmd VimEnter * NERDTree | wincmd p

" Select the file in the NERDTree when it is opened
autocmd BufWinEnter * if &buftype != 'quickfix' && getcmdwintype() == '' | silent NERDTreeMirror | endif

" Load the plugins when entering vim
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Search for a file using Ag
map <S-f> :Files<CR>
" Split the screen and search for a file using Ag
map <C-Left> :vnew<CR>:Files<CR>
map <C-Up> :new<CR>:Files<CR>
" Toggle NERDTree using Space
nmap , :NERDTreeToggle<CR>
" Toggle Tagbar using Ctrl + t
nmap <C-t> :TagbarToggle<CR>

" Move between splits using Ctrl + h/j/k/l
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Remap esc to kj
inoremap kj <Esc>
vnoremap kj <Esc>
cnoremap kj <C-C>

" Disable esc key for muscle memory
inoremap <Esc> <Nop>

" Search for a word using Ctrl + f
nmap     <C-F>f <Plug>CtrlSFPrompt
vmap     <C-F>f <Plug>CtrlSFVwordPath

" Map ctrl + C to copy, middle mouse button to paste
nmap <C-c> "+y

" Mapping for easy motion
" Define leader as space
let mapleader = " "

nmap f <Plug>(easymotion-overwin-f2)
map <Leader>j <Plug>(easymotion-bd-jk)
nmap <Leader>j <Plug>(easymotion-overwin-line)

map / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)

let g:EasyMotion_smartcase = 1

" After selecting a file in the search, focus on it when opened
let g:ctrlsf_auto_focus = {
    \ "at": "start"
    \ }

" Add the filename to the status line
let g:lightline = {
      \ 'component_function': {
      \   'filename': 'FilenameForLightline'
      \ }
      \ }

" Show full path of filename
function! FilenameForLightline()
    return expand('%')
endfunction

" Map a key to preview the markdown file
nmap <F4> :call PreviewMarkdown()<CR>clear<CR>glow $(cat ~/.lastpreview.log)<CR>

" Search option is compact, when expanded, do it on the right
let g:ctrlsf_default_view_mode = 'compact'
let g:ctrlsf_search_mode = 'async'
let g:ctrlsf_position = 'right'

" YouCompleteMe
nnoremap <silent><leader>] :YcmCompleter GoTo<CR>
nnoremap <silent><leader>p :YcmCompleter GoToReferences<CR>
nnoremap <silent><leader>t :YcmCompleter GetType<CR>
nnoremap <silent><leader>f :YcmCompleter FixIt<CR>
nnoremap <silent><leader>r :execute 'YcmCompleter RefactorRename ' . input('Rename to: ')<CR>
nnoremap <silent><leader>o :YcmCompleter GoToAlternateFile<CR>

" Remove popup when hovering functions
let g:ycm_auto_hover=''

" Change mark recall for simplicity
nnoremap <leader>m '

" Airline theme
let g:airline_theme='base16_gruvbox_dark_hard'

" Remove lua support from polyglot to avoid loading errors on some files
let g:polyglot_disabled = ['lua']

" C++ better highlight
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_posix_standard = 1

" C++ ALE options
let g:ale_pattern_options_enabled = 1
let g:ale_linters_explicit = 1
let opts = '-std=c++17 -Wall -Wextra --compile-commands-dir=./build-Debug'
let g:ale_pattern_options = {
\   '\.h$':   { 'ale_linters': { 'cpp': ['clangd', 'cppcheck', 'clangtidy'] } },
\   '\.c$':   { 'ale_linters': { 'cpp': ['clangd', 'cppcheck', 'clangtidy'] } },
\   '\.cpp$': { 'ale_linters': { 'cpp': ['clangd', 'cppcheck', 'clangtidy'] } },
\   '\.hpp$': { 'ale_linters': { 'cpp': ['clangd', 'cppcheck', 'clangtidy'] } },
\}
let g:ale_linters = { 'cpp': ['clangd', 'cppcheck', 'clangtidy'] }
let g:ale_cpp_cc_options    = opts
let g:ale_cpp_gcc_options   = opts
let g:ale_cpp_clang_options = opts
let g:ale_cpp_clangd_options = opts
let g:ale_cpp_clangtidy_options = opts
let g:ale_fix_on_save = 1
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1

" workspace plugin
let g:workspace_autocreate = 1
let g:workspace_session_directory = expand('$HOME/.vim/workspace')
let g:workspace_undodir = expand('$HOME/.vim/workspace/.undodir')

if !isdirectory(g:workspace_undodir)
    call mkdir(g:workspace_undodir, 'p')
endif

set undofile
set undodir^=~/.vim/workspace/.undodir

" Gutentags plugi
let g:gutentags_add_default_project_roots = 0
let g:gutentags_project_root = ['.git']

let g:gutentags_cache_dir = expand('~/.cache/vim/ctags/')

let g:gutentags_generate_on_new = 1
let g:gutentags_generate_on_missing = 1
let g:gutentags_generate_on_write = 1
let g:gutentags_generate_on_empty_buffer = 0

let g:gutentags_ctags_extra_args = [
      \ '--tag-relative=yes',
      \ '--fields=+ailmnS',
      \ ]

let g:gutentags_ctags_exclude = [
      \ '*.git', '*.svg', '*.hg',
      \ '*/tests/*',
      \ 'build',
      \ 'dist',
      \ '*sites/*/files/*',
      \ 'bin',
      \ 'node_modules',
      \ 'bower_components',
      \ 'cache',
      \ 'compiled',
      \ 'docs',
      \ 'example',
      \ 'bundle',
      \ 'vendor',
      \ '*.md',
      \ '*-lock.json',
      \ '*.lock',
      \ '*bundle*.js',
      \ '*build*.js',
      \ '.*rc*',
      \ '*.json',
      \ '*.min.*',
      \ '*.map',
      \ '*.bak',
      \ '*.zip',
      \ '*.pyc',
      \ '*.class',
      \ '*.sln',
      \ '*.Master',
      \ '*.csproj',
      \ '*.tmp',
      \ '*.csproj.user',
      \ '*.cache',
      \ '*.pdb',
      \ 'tags*',
      \ 'cscope.*',
      \ '*.css',
      \ '*.less',
      \ '*.scss',
      \ '*.exe', '*.dll',
      \ '*.mp3', '*.ogg', '*.flac',
      \ '*.swp', '*.swo',
      \ '*.bmp', '*.gif', '*.ico', '*.jpg', '*.png',
      \ '*.rar', '*.zip', '*.tar', '*.tar.gz', '*.tar.xz', '*.tar.bz2',
      \ '*.pdf', '*.doc', '*.docx', '*.ppt', '*.pptx',
      \ ]


" Default view method for vimtex
let g:vimtex_view_method = 'zathura'

" Apply Ctags to the project when it is modified
autocmd BufWritePost *.c,*.h,*.cpp,*.hpp silent! !ctags -R . &

" Swap between header and source
" map <Esc>o <A-o>
" nnoremap <A-o> :call CurtineIncSw()<CR>

" Call the search for the inner word under the cursor
nnoremap <C-p> viw<Plug>CtrlSFVwordPath

" Tab commands on shift + t/j/k/q
map <S-t> :tabnew<CR>
map <S-j> :tabnext<CR>
map <S-k> :tabprevious<CR>
map <S-q> :tabclose<CR>

" hightlight all the words similar to the one under the cursor
augroup hightlight_current_word
  au!
  autocmd CursorHold * :exec 'match Search /\V\<'. escape(expand('<cword>'), '\\/.*$^~[]') . '\>/'
augroup END

" Split directions
set splitright
set splitbelow

" Command functions to search and open buffers using fzf
command! Buffers call fzf#run(fzf#wrap('buffers', {
      \ 'source': map(filter(range(1, bufnr('$')), 'buflisted(v:val)'), 'bufname(v:val)'),
      \ 'sink':   'edit'
      \ }))

command! BuffersSplit call fzf#run(fzf#wrap('buffers', {
      \ 'source': map(filter(range(1, bufnr('$')), 'buflisted(v:val)'), 'bufname(v:val)'),
      \ 'sink':   { buf -> execute('split ' . buf) }
      \ }))

command! BuffersVSplit call fzf#run(fzf#wrap('buffers', {
      \ 'source': map(filter(range(1, bufnr('$')), 'buflisted(v:val)'), 'bufname(v:val)'),
      \ 'sink':   { buf -> execute('vsplit ' . buf) }
      \ }))

" Remap calls to open buffers
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>sp :BuffersSplit<CR>
nnoremap <leader>vs :BuffersVSplit<CR>

" Source the plugins in the plugins.vim file
so ~/.vim/plugins.vim

" Load the color scheme and their settings at the end of the file to allow the
" plugins to load first
colorscheme gruvbox-material

" set the highlight color of a search
highlight Search cterm=bold,italic,underline ctermbg=NONE ctermfg=lightblue

" set the highlight color of various components
highlight String ctermfg=109
highlight cCustomClass ctermfg=214
highlight cCustomClassName ctermfg=214

" set the update time to 300ms
set updatetime=300
